### ISSUE TITLE
Script certified_validate.sh não funciona como deveria

### ISSUE THREAD

**Issue by fmonticelli** [DennisNgrox/Shell-Scripting#1]
### Dessa maneira aqui funciona :smiley:

```bash
#!/bin/bash

host="$1"
if [ -z "$2" ]
then
          port=443
  else
            port=$2
fi

notAfter=$(openssl s_client -connect $host:$port < /dev/null 2> /dev/null | openssl x509 -in /dev/stdin -noout -dates | grep notAfter | cut -d'=' -f2)
expire=$(date -d "$notAfter" +%s)
today=$(date --utc +%s)
left_seconds=$((expire - today))
left_days=$((left_seconds/60/60/24))

echo "$left_days"
```

**Comment by DennisNgrox** [comment]
Acabei de realizar o teste novamente do script, funcionou normal, qual
seria o problema?

[image: image.png]

Rodei também o seu script ao qual vc colocou a variavel NotAfter na
variavel expire... retornou o mesmo resultado

[image: image.png]

Em ter., 18 de abr. de 2023 às 12:57, fmonticelli ***@***.***>
escreveu:

**Comment by DennisNgrox** [comment]
Ah vi o problema

Na hora que copiei ele não copiou o resto do comando kkkkkkkk


Agradeço!!!!

Em ter., 18 de abr. de 2023 às 12:57, fmonticelli ***@***.***>
escreveu:

**Comment by fmonticelli** [comment]
Vi por acaso teu post no linkedin, acessei o repo, curti e resolvi testar esse pq me chamou atenção... o resto é história kkk

**Comment by DennisNgrox** [comment]
Agradeço mano!!!

Em qui., 20 de abr. de 2023 às 18:02, fmonticelli ***@***.***>
escreveu:
